// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sequencer.dart';
import 'api/synth.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RushSynthLib
    extends
        BaseEntrypoint<RushSynthLibApi, RushSynthLibApiImpl, RushSynthLibWire> {
  @internal
  static final instance = RushSynthLib._();

  RushSynthLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RushSynthLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RushSynthLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RushSynthLibApiImpl, RushSynthLibWire>
  get apiImplConstructor => RushSynthLibApiImpl.new;

  @override
  WireConstructor<RushSynthLibWire> get wireConstructor =>
      RushSynthLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -507580927;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rush_synth',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RushSynthLibApi extends BaseApi {
  Future<bool> crateApiSequencerRushSequencerEndOfSequence({
    required RushSequencer that,
  });

  Future<RushSequencer> crateApiSequencerRushSequencerNew({
    required String soundfontPath,
  });

  Future<void> crateApiSequencerRushSequencerPlay({
    required RushSequencer that,
    required String midiPath,
    required bool playLoop,
  });

  Future<void> crateApiSequencerRushSequencerSetSpeed({
    required RushSequencer that,
    required double speed,
  });

  Future<void> crateApiSequencerRushSequencerStop({
    required RushSequencer that,
  });

  Future<void> crateApiSynthRushSynthAllNotesOff({required RushSynth that});

  Future<RushSynth> crateApiSynthRushSynthNew({required String soundfontPath});

  Future<void> crateApiSynthRushSynthNoteOff({
    required RushSynth that,
    required int channel,
    required int key,
  });

  Future<void> crateApiSynthRushSynthNoteOn({
    required RushSynth that,
    required int channel,
    required int key,
    required int velocity,
  });

  Future<void> crateApiSynthRushSynthPause({required RushSynth that});

  Future<void> crateApiSynthRushSynthStart({required RushSynth that});

  Future<void> crateApiSynthRushSynthStop({required RushSynth that});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RushSequencer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RushSequencer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RushSequencerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RushSynth;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RushSynth;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RushSynthPtr;
}

class RushSynthLibApiImpl extends RushSynthLibApiImplPlatform
    implements RushSynthLibApi {
  RushSynthLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiSequencerRushSequencerEndOfSequence({
    required RushSequencer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSequencerRushSequencerEndOfSequenceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSequencerRushSequencerEndOfSequenceConstMeta =>
      const TaskConstMeta(
        debugName: "RushSequencer_end_of_sequence",
        argNames: ["that"],
      );

  @override
  Future<RushSequencer> crateApiSequencerRushSequencerNew({
    required String soundfontPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(soundfontPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSequencerRushSequencerNewConstMeta,
        argValues: [soundfontPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSequencerRushSequencerNewConstMeta =>
      const TaskConstMeta(
        debugName: "RushSequencer_new",
        argNames: ["soundfontPath"],
      );

  @override
  Future<void> crateApiSequencerRushSequencerPlay({
    required RushSequencer that,
    required String midiPath,
    required bool playLoop,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
            that,
            serializer,
          );
          sse_encode_String(midiPath, serializer);
          sse_encode_bool(playLoop, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSequencerRushSequencerPlayConstMeta,
        argValues: [that, midiPath, playLoop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSequencerRushSequencerPlayConstMeta =>
      const TaskConstMeta(
        debugName: "RushSequencer_play",
        argNames: ["that", "midiPath", "playLoop"],
      );

  @override
  Future<void> crateApiSequencerRushSequencerSetSpeed({
    required RushSequencer that,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
            that,
            serializer,
          );
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSequencerRushSequencerSetSpeedConstMeta,
        argValues: [that, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSequencerRushSequencerSetSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "RushSequencer_set_speed",
        argNames: ["that", "speed"],
      );

  @override
  Future<void> crateApiSequencerRushSequencerStop({
    required RushSequencer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSequencerRushSequencerStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSequencerRushSequencerStopConstMeta =>
      const TaskConstMeta(debugName: "RushSequencer_stop", argNames: ["that"]);

  @override
  Future<void> crateApiSynthRushSynthAllNotesOff({required RushSynth that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSynthRushSynthAllNotesOffConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthAllNotesOffConstMeta =>
      const TaskConstMeta(
        debugName: "RushSynth_all_notes_off",
        argNames: ["that"],
      );

  @override
  Future<RushSynth> crateApiSynthRushSynthNew({required String soundfontPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(soundfontPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSynthRushSynthNewConstMeta,
        argValues: [soundfontPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthNewConstMeta => const TaskConstMeta(
    debugName: "RushSynth_new",
    argNames: ["soundfontPath"],
  );

  @override
  Future<void> crateApiSynthRushSynthNoteOff({
    required RushSynth that,
    required int channel,
    required int key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          sse_encode_i_32(channel, serializer);
          sse_encode_i_32(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSynthRushSynthNoteOffConstMeta,
        argValues: [that, channel, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthNoteOffConstMeta =>
      const TaskConstMeta(
        debugName: "RushSynth_note_off",
        argNames: ["that", "channel", "key"],
      );

  @override
  Future<void> crateApiSynthRushSynthNoteOn({
    required RushSynth that,
    required int channel,
    required int key,
    required int velocity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          sse_encode_i_32(channel, serializer);
          sse_encode_i_32(key, serializer);
          sse_encode_i_32(velocity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSynthRushSynthNoteOnConstMeta,
        argValues: [that, channel, key, velocity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthNoteOnConstMeta =>
      const TaskConstMeta(
        debugName: "RushSynth_note_on",
        argNames: ["that", "channel", "key", "velocity"],
      );

  @override
  Future<void> crateApiSynthRushSynthPause({required RushSynth that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSynthRushSynthPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthPauseConstMeta =>
      const TaskConstMeta(debugName: "RushSynth_pause", argNames: ["that"]);

  @override
  Future<void> crateApiSynthRushSynthStart({required RushSynth that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSynthRushSynthStartConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthStartConstMeta =>
      const TaskConstMeta(debugName: "RushSynth_start", argNames: ["that"]);

  @override
  Future<void> crateApiSynthRushSynthStop({required RushSynth that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSynthRushSynthStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSynthRushSynthStopConstMeta =>
      const TaskConstMeta(debugName: "RushSynth_stop", argNames: ["that"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RushSequencer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RushSequencer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RushSynth => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RushSynth => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RushSequencer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSequencerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSynth
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSynthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSequencer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSequencerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSynth
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSynthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSequencer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSequencerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSynth
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSynthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSequencer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSequencerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RushSynth
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RushSynthImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RushSequencer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSequencerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSynth
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSynthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSequencer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSequencerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSynth
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSynthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSequencer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSequencerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSynth
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSynthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSequencer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSequencerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RushSynth
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RushSynthImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    RushSequencer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSequencerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    RushSynth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSynthImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    RushSequencer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSequencerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    RushSynth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSynthImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    RushSequencer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSequencerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    RushSynth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSynthImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSequencer(
    RushSequencer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSequencerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRushSynth(
    RushSynth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RushSynthImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RushSequencerImpl extends RustOpaque implements RushSequencer {
  // Not to be used by end users
  RushSequencerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RushSequencerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RushSynthLib.instance.api.rust_arc_increment_strong_count_RushSequencer,
    rustArcDecrementStrongCount:
        RushSynthLib.instance.api.rust_arc_decrement_strong_count_RushSequencer,
    rustArcDecrementStrongCountPtr: RushSynthLib
        .instance
        .api
        .rust_arc_decrement_strong_count_RushSequencerPtr,
  );

  Future<bool> endOfSequence() => RushSynthLib.instance.api
      .crateApiSequencerRushSequencerEndOfSequence(that: this);

  Future<void> play({required String midiPath, required bool playLoop}) =>
      RushSynthLib.instance.api.crateApiSequencerRushSequencerPlay(
        that: this,
        midiPath: midiPath,
        playLoop: playLoop,
      );

  Future<void> setSpeed(double speed) => RushSynthLib.instance.api
      .crateApiSequencerRushSequencerSetSpeed(that: this, speed: speed);

  Future<void> stop() =>
      RushSynthLib.instance.api.crateApiSequencerRushSequencerStop(that: this);
}

@sealed
class RushSynthImpl extends RustOpaque implements RushSynth {
  // Not to be used by end users
  RushSynthImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RushSynthImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RushSynthLib.instance.api.rust_arc_increment_strong_count_RushSynth,
    rustArcDecrementStrongCount:
        RushSynthLib.instance.api.rust_arc_decrement_strong_count_RushSynth,
    rustArcDecrementStrongCountPtr:
        RushSynthLib.instance.api.rust_arc_decrement_strong_count_RushSynthPtr,
  );

  Future<void> allNotesOff() =>
      RushSynthLib.instance.api.crateApiSynthRushSynthAllNotesOff(that: this);

  /// Turn a MIDI note off
  /// channel: MIDI channel (0-15)
  /// key: MIDI key (0-127)
  Future<void> noteOff({required int channel, required int key}) => RushSynthLib
      .instance
      .api
      .crateApiSynthRushSynthNoteOff(that: this, channel: channel, key: key);

  /// channel: MIDI channel (0-15)
  /// key: MIDI key (0-127)
  /// velocity: MIDI velocity (0-127)
  Future<void> noteOn({
    required int channel,
    required int key,
    required int velocity,
  }) => RushSynthLib.instance.api.crateApiSynthRushSynthNoteOn(
    that: this,
    channel: channel,
    key: key,
    velocity: velocity,
  );

  /// Pause the stream without releasing resources
  Future<void> pause() =>
      RushSynthLib.instance.api.crateApiSynthRushSynthPause(that: this);

  /// Start a new stream or resume a paused stream
  Future<void> start() =>
      RushSynthLib.instance.api.crateApiSynthRushSynthStart(that: this);

  /// Stop the stream and release resources
  Future<void> stop() =>
      RushSynthLib.instance.api.crateApiSynthRushSynthStop(that: this);
}
