// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `fill_output_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RushSequencer>>
abstract class RushSequencer implements RustOpaqueInterface {
  Future<bool> endOfSequence();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RushSequencer> newInstance({required String soundfontPath}) =>
      RushSynthLib.instance.api.crateApiSequencerRushSequencerNew(
        soundfontPath: soundfontPath,
      );

  Future<void> play({required String midiPath, required bool playLoop});

  Future<void> setSpeed(double speed);

  Future<void> stop();
}
