// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../util.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `fill_output_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RushSequencer>>
abstract class RushSequencer implements RustOpaqueInterface {
  /// Gets a value that indicates whether the current playback position is at the end of the sequence.
  /// If the `play` method has not yet been called, this value will be `true`.
  /// This value will never be `true` if loop playback is enabled.
  bool get endOfSequence;

  /// Create a new RushSequencer using a soundfont from the file system.
  static Future<RushSequencer> fromFile(String soundfontPath) => RushSynthLib
      .instance
      .api
      .crateApiSequencerRushSequencerFromFile(soundfontPath: soundfontPath);

  /// Play a MIDI file.
  Future<void> play({required String midiPath, bool playLoop = false});

  /// Gets the current playback position in seconds.
  double get position;

  /// Set playback speed.
  /// 1.0 means normal speed derived from the tempo and ticksPerBeat in MIDI file.
  /// The tempo will be multiplied by this value during playback.
  Future<void> setSpeed(double speed);

  /// Stop playing the current MIDI file.
  Future<void> stop();

  /// Create a new RushSequencer using a soundfont from the assets bundle.
  static Future<RushSequencer> fromAsset(String asset) async =>
      RushSequencer.fromFile(await loadAsset(asset));
}
