// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `fill_output_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RushSynth>>
abstract class RushSynth implements RustOpaqueInterface {
  Future<void> allNotesOff();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RushSynth> newInstance({required String soundfontPath}) =>
      RustLib.instance.api.crateApiSynthRushSynthNew(
        soundfontPath: soundfontPath,
      );

  Future<void> noteOff({required int channel, required int key});

  /// channel: MIDI channel (0-15)
  /// key: MIDI key (0-127)
  /// velocity: MIDI velocity (0-127)
  Future<void> noteOn({
    required int channel,
    required int key,
    required int velocity,
  });

  Future<void> pause();

  Future<void> start();

  Future<void> stop();
}
