// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../util.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `build_stream`, `fill_output_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RushSynth>>
abstract class RushSynth implements RustOpaqueInterface {
  /// Turn off all MIDI notes that are on
  Future<void> allNotesOff();

  /// Create a new RushSynth using a soundfont from the file system.
  static Future<RushSynth> fromFile(String soundfontPath) => RushSynthLib
      .instance
      .api
      .crateApiSynthRushSynthFromFile(soundfontPath: soundfontPath);

  /// Turn a MIDI note off
  ///
  /// # Arguments
  ///
  /// * `channel` - The channel of the note.
  /// * `key` - The key of the note.
  Future<void> noteOff({required int channel, required int key});

  /// Turn a MIDI note on.
  ///
  /// # Arguments
  ///
  /// * `channel` - The channel of the note.
  /// * `key` - The key of the note.
  /// * `velocity` - The velocity of the note.
  Future<void> noteOn({
    required int channel,
    required int key,
    required int velocity,
  });

  /// Pause the stream without releasing resources.
  Future<void> pause();

  /// Start a new stream or resume a paused stream.
  Future<void> start();

  /// Stop the stream and release resources
  Future<void> stop();

  /// Create a new RushSynth using a soundfont from the assets bundle.
  static Future<RushSynth> fromAsset(String asset) async =>
      RushSynth.fromFile(await loadAsset(asset));
}
